README.md

`flatpickr` supports a manual locale configuration. E.g. `moment.js` locale config can be used without having to load additional locale info.

Add docs for custom locale config support.

---

addon/components/ember-flatpickr.js

I haven't supplied defaults in `ember-flatpickr`; flatpickr will provide its own defaults if the values are `undefined`.

(fix) Pass `defaultHour` and `defaultMinute` to flatpickr

---

index.js
package.json
yarn.lock

This should make the addon compatible to fastboot 1.0 mentioned in https://github.com/ember-fastboot/ember-cli-fastboot/issues/387
@rwwagner90 I don't know how this addon is supposed to work. So I haven't tested this addon with and without fastboot addon. Please make sure to test to test it before merging.

Prepare for FastBoot 1.0.

---

README.md

This section is no longer relavant after:
https://github.com/shipshapecode/ember-flatpickr/commit/b89bfa782e13e99441d2f791e2fcb685fbdd6da5

Update 'observer' section of readme

---

README.md
addon-test-support/helpers.js
package.json

I've been using ember-flatpickr a bit in my latest project and I've found myself repeating a few patterns when writing tests that involve the library. In an effort to keep things organized and hopefully set precedent for any future test helpers, I've converted my personal helpers into an add-on test-support file. I've also updated the ReadMe to with basic usage instructions (I've left out usage for each specific helper as I think the JS annotations have that covered).
These helpers aren't anything monumental but I figure they can spark some discussion, at the very least. Let me know what you think.

Adding test helpers

---

package.json
yarn.lock

This just bumps `ember-diff-attrs` to address the deprecation warning outlined here: #229

updating ember-diff-attrs to avoid deprecation warning

---

addon/components/ember-flatpickr.js
tests/integration/components/ember-flatpickr-test.js

Implements #264.
There are two caveats about this code.
1) It uses placeholder methods instead of directly referencing the functions because `bind(this)` would break if the user changed the action attached dynamically. Code could be reduced if this is not a worry.
2) It is not backwards compatible below 1.13.

Remove deprecated sendAction

---

addon/components/ember-flatpickr.js
tests/integration/components/ember-flatpickr-test.js

Fixes https://github.com/shipshapecode/ember-flatpickr/issues/255
So the test actually fails because flatpickr itself doesn't currently update altFormat for some reason. I have made them aware of the issue here;
https://github.com/flatpickr/flatpickr/issues/1431
So this PR is just in preparation for when that issue is fixed - it should work once that's done.
-----
Unrelated, a different test about locales was failing too
```
not ok 16 Chrome 67.0 - Integration | Component | ember flatpickr: locale works correctly
actual: > décembre
expected: >Décembre
```

ember-flatpickr now observes changes to altFormat attr

---

index.js

In order to let other ui libs such as `ember-paper` use `ember-flatpickr` via third addons integrations like `ember-paper-flatpickr` the host app via `ember-cli-build.js` should be able to define `flatpickr` options, like the theme or locales, as normal `ember-flatpickr` do... so this PR makes sure we find the host app, so we can access the `app.options.flatpickr` options.
It's actually a copy paste from `ember-paper` `include` hook.

_findHost in included for third addons

---

addon/mixins/flatpickr.js
tests/dummy/app/templates/docs/usage.md
tests/integration/components/ember-flatpickr-test.js

Currently access to the flatpickrRef is only done via two-way binding which is against DDAU. This also prevents the component being used with angle-bracket syntax.
Created an action onFlatpickrRef to replace the two-way binding.

Allow flatpickrRef access via an action

---

addon/mixins/flatpickr.js
tests/dummy/app/templates/docs/usage.md

The wrap option, if passed as true to flatpickr, will fail with an error because ember-flatpickr has not ability to attach to a parent element. I played with what it would take to make this feasible and it just complicated the component needlessly. Considering that the same thing could be done easily, I updated the documentation with an example, and added an assert on wrap=true (since it would fail) and pointed the user to the documentation.

Prevent wrap. Provide documentation

---

addon/components/ember-flatpickr.js
addon/mixins/flatpickr.js
package.json
tests/integration/components/ember-flatpickr-test.js
yarn.lock

* Started by introducing ARIA attribute bindings
* Noticed that the `title` attribute wasn't bound to this control, thought it odd
* Instead of extending `Component` changed to extend `TextField` (I've done this many times in other projects)
* Extending `TextField` necessitated a small change in the `_setDisabled` when `altInput` is used
* fumbled around by adding some yuidoc

🌐♻️📝Adding Some ARIA Support + Extending Ember TextField + Docs

---

addon/components/ember-flatpickr.js
package.json
tests/dummy/app/templates/docs/components/ember-flatpickr.md
tests/dummy/app/templates/docs/usage.md
tests/integration/components/ember-flatpickr-test.js
yarn.lock

Updated `flatpickr` to v4.6.6, fix failing tests by changing all `mousedown` events to `click` events, and removed the `date` class property as it is not being used anywhere in the class. The actual date object is in the `this.args` object.

Remove `getFlatpickrRef` and `appendDataInput`, update flatpickr to 4.6.6

---

tests/dummy/app/templates/docs/usage.md

I noticed there was a missing URL in the documentation code example.
There was also a broken URL.

Fixed code typo and broken URL

---

tests/dummy/app/templates/docs/usage.md

updated the documentation example surrounding external elements noting that users will need to stopPropagation on click events in order for FlatPickr to properly open the calendar popup

[docs] Updated documentation regarding external elements

---

index.js

Use require.resolve to handle when node_modules might be elsewhere like with yarn workspaces

compatibility with workspaces

---

addon/components/ember-flatpickr.ts
tests/integration/components/ember-flatpickr-test.js

We would like to wrap `<EmberFlatpickr>` in a component to DRY up some of the config options that we pass to every instance. Because Ember doesn't have "splargs" (a la splattributes), this means we end up having to pass through every possible Ember Flatpickr arg like so:
```hbs
<EmberFlatpickr
class="w-full block border-2 p-3 mb-2"
placeholder="Choose a date"
...attributes
@allowInput={{or-default @allowInput true}}
@altFormat={{@altFormat}}
@altInput={{or-default @altInput true}}
@altInputClass={{@altInputClass}}
@clickOpens={{@clickOpens}}
@date={{@date}}
@dateFormat={{@dateFormat}}
@defaultDate={{@defaultDate}}
@defaultHour={{@defaultHour}}
@defaultMinute={{@defaultMinute}}
@disable={{@disable}}
@disabled={{@disabled}}
@disableMobile={{@disableMobile}}
@enable={{@enable}} …
```

Don't pass undefined arguments through to Flatpickr config

---

addon/components/ember-flatpickr.ts

Resolves this deprecation
```
deprecate.js:136 DEPRECATION: Using `run.scheduleOnce` has been deprecated. Instead, import the value directly from @ember/runloop:
import { scheduleOnce } from '@ember/runloop'; [deprecation id: deprecated-run-loop-and-computed-dot-access]
```

fix: run.scheduleOnce import deprecation

---

addon-test-support/helpers.js
tests/integration/components/ember-flatpickr-test.js

add ability to pass an html element to test helpers

---

ember-flatpickr/src/test-support/helpers.js

Stumbled upon this piece of code. Maybe it's time to remove it ?

Remove old registerHelper in favor of importing helpers directly

---

ember-flatpickr/src/components/ember-flatpickr.ts

If `"en"` is passed as locale to the `<EmberFlatpickr />` component, the addon will try importing a file `flatpickr/dist/l10n/en.js` which does not exist as English is the default language that is included in the core and doesn't need to be imported additionally.

fix(locale): don't try dynamically importing the default locale

---

test-app/app/templates/docs/localization.md

Cleanup localization documentation

---

ember-flatpickr/package.json
ember-flatpickr/src/components/ember-flatpickr.ts
pnpm-lock.yaml
test-app/tests/integration/components/ember-flatpickr-test.js

After updating `ember-flatpickr` from version `4.0.0` to `8.0.0`, several rendering and application tests, which assert that the `flatpickr` calendar works (e.g. the user can see the correct date initially, they can click the input to open the calendar and select a date), became flaky.
I believe the reason is, we need translations for Germany to exist (for these assertions to pass) and have been passing the argument `@locale="de"`. Since `ember-flatpickr@>=7.1.0` uses dynamic import to load the translations, tests can fail when loading takes a while. We can see this issue happen by throttling the network when running the tests for `ember-flatpickr`.
Wrap the dynamic `import()` with `waitForPromise()` from [`@ember/test-waiters`](https://github.com/emberjs/ember-test-waiters), so that …

bugfix: Waited for dynamic import to resolve
